export const AUTH_ERROR_CODES = {
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCESS_DENIED: "ACCESS_DENIED",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

export const USER_ROLES = {
  ADMINISTRADOR: "ADMINISTRADOR",
  INVENTARIO: "INVENTARIO",
  VENDEDOR: "VENDEDOR",
  COLABORADOR: "COLABORADOR",
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

export const ROLE_GROUPS = {
  ADMIN_ONLY: [USER_ROLES.ADMINISTRADOR],
  INVENTORY_ACCESS: [USER_ROLES.ADMINISTRADOR, USER_ROLES.INVENTARIO],
  POS_ACCESS: [USER_ROLES.ADMINISTRADOR, USER_ROLES.VENDEDOR],
} as const satisfies Record<string, UserRole[]>;
